# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Test
email: jstanley@mitre.org
description: >- # this means to ignore newlines until "baseurl:"
  tbd
baseurl: "/chatbot-accessibility-playbook" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
color_scheme: light
#plugins:
#  - jekyll-feed

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust
# markup / liquid-based content.
footer_content: "Copyright (c) 2021 The MITRE Corporation. All Rights Reserved."
gh_edit_link: false # show or hide edit this page link

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - vendor
  
# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
    "Edit me in Gitlab":
      - "https://gitlab.mitre.org/jstanley/chatbot-accessibility-playbook"

